import 'package:fidefund/models/milestone_model.dart';
import 'package:fidefund/utils/app_images.dart';

class MilestoneController {
  static List<Milestone> mockMilestone = [
    Milestone(
      id: "1",
      title: "Saving Stray Dogs in Melaka",
      description: "A campaign to save stray dogs...",
      order: 1,
      // category: "Animal Welfare",
      contributors: 120,
      raisedAmount: 5000,
      targetAmount: 10000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneStraydogs,
      createdAt: DateTime(2025, 3, 14),
    ),
    Milestone(
      id: "2",
      title: "E-Gadgets for B40 Students",
      description: "Providing gadgets for underprivileged students...",
      order: 2,
      // category: "Education",
      contributors: 200,
      raisedAmount: 8000,
      targetAmount: 15000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneGadgets,
      createdAt: DateTime(2025, 3, 10),
    ),
    Milestone(
      id: "3",
      title: "Flood in East Coast Malaysia",
      description: "Flood relief for affected families...",
      order: 1,
      // category: "Disaster Relief",
      contributors: 300,
      raisedAmount: 12000,
      targetAmount: 20000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneFlood,
      createdAt: DateTime(2025, 2, 7),
    ),
  ];

  static List<Milestone> milestonesDogs = [
    // Saving Stray Dogs in Melaka
    Milestone(
      id: "1_0",
      title: "Rescue Initial Strays",
      description: "Rescue 10 stray dogs and provide medical care.",
      order: 1,
      contributors: 120,
      targetAmount: 10000,
      raisedAmount: 5000,
      isComplete: true,
      coverImage: AppImages.imageCharityDogs,
      image: [],
      document: [],
      createdAt: DateTime(2025, 3, 14),
    ),
    Milestone(
      id: "1_1",
      title: "Build Temporary Shelter",
      description: "Set up a temporary shelter for rescued dogs.",
      order: 2,
      contributors: 120,
      targetAmount: 10000,
      raisedAmount: 5000,
      isComplete: false,
      coverImage: AppImages.imageCharityDogs,
      image: [],
      document: [],
      createdAt: DateTime(2025, 3, 14),
    ),
    Milestone(
      id: "1_2",
      title: "Launch Adoption Drive",
      description: "Find permanent homes for rehabilitated dogs.",
      order: 3,
      contributors: 120,
      targetAmount: 10000,
      raisedAmount: 5000,
      isComplete: false,
      coverImage: AppImages.imageCharityDogs,
      image: [],
      document: [],
      createdAt: DateTime(2025, 3, 14),
    ),
  ];

  static List<Milestone> milestonesGadgets = [
    // E-Gadgets for B40 Students
    Milestone(
      id: "2_0",
      title: "Fundraising Kickoff",
      description: "Raise initial funds for purchasing gadgets.",
      order: 1,
      contributors: 200,
      targetAmount: 15000,
      raisedAmount: 8000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneGadgets,
      image: [],
      document: [],
      createdAt: DateTime(2025, 3, 10),
    ),
    Milestone(
      id: "2_1",
      title: "Procure Laptops & Tablets",
      description: "Purchase 50 laptops and 100 tablets.",
      order: 2,
      contributors: 200,
      targetAmount: 15000,
      raisedAmount: 8000,
      isComplete: false,
      coverImage: AppImages.imageMilestoneGadgets,
      image: [],
      document: [],
      createdAt: DateTime(2025, 3, 10),
    ),
    Milestone(
      id: "2_2",
      title: "Distribution to Schools",
      description: "Deliver gadgets to selected schools.",
      order: 3,
      contributors: 200,
      targetAmount: 15000,
      raisedAmount: 8000,
      isComplete: false,
      coverImage: AppImages.imageMilestoneGadgets,
      image: [],
      document: [],
      createdAt: DateTime(2025, 3, 10),
    ),
    Milestone(
      id: "2_3",
      title: "Technical Support & Training",
      description: "Provide guidance on device usage.",
      order: 4,
      contributors: 200,
      targetAmount: 15000,
      raisedAmount: 8000,
      isComplete: false,
      coverImage: AppImages.imageMilestoneGadgets,
      image: [],
      document: [],
      createdAt: DateTime(2025, 3, 10),
    ),
  ];

  static List<Milestone> milestonesFlood = [
    Milestone(
      id: "3_0",
      title: "Distribute Emergency Kits",
      description: "Provide food and essential items.",
      order: 1,
      contributors: 300,
      targetAmount: 20000,
      raisedAmount: 12000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneFlood,
      image: [],
      document: [],
      createdAt: DateTime(2025, 2, 7),
    ),
    Milestone(
      id: "3_1",
      title: "Set Up Evacuation Centers",
      description: "Organize temporary shelters.",
      order: 2,
      contributors: 300,
      targetAmount: 20000,
      raisedAmount: 12000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneFlood,
      image: [],
      document: [],
      createdAt: DateTime(2025, 2, 7),
    ),
    Milestone(
      id: "3_2",
      title: "Long-Term Housing Support",
      description: "Assist families in rebuilding homes.",
      order: 3,
      contributors: 300,
      targetAmount: 20000,
      raisedAmount: 12000,
      isComplete: false,
      coverImage: AppImages.imageMilestoneFlood,
      image: [AppImages.imageMilestoneFlood, AppImages.imageMilestoneFlood1, 
        AppImages.imageMilestoneFlood2, AppImages.imageMilestoneFlood3, AppImages.imageMilestoneFlood4],
      document: [],
      createdAt: DateTime(2025, 2, 7),
    ),
  ];

  static List<Milestone> milestoneTree = [
    Milestone(
      id: "1",
      title: "Secure Land for Planting",
      description: "Obtain approval for planting sites.",
      order: 1,
      contributors: 0,
      raisedAmount: 0,
      targetAmount: 0,
      isComplete: true,
      coverImage: AppImages.imageMilestoneTrees,
      createdAt: DateTime.now(),
    ),
    Milestone(
      id: "2",
      title: "Tree Sapling Procurement",
      description: "Purchase and transport saplings.",
      order: 2,
      contributors: 0,
      raisedAmount: 0,
      targetAmount: 0,
      isComplete: false,
      coverImage: AppImages.imageMilestoneTrees,
      createdAt: DateTime.now(),
    ),
    Milestone(
      id: "3",
      title: "Community Planting Event",
      description: "Engage volunteers in tree planting.",
      order: 3,
      contributors: 0,
      raisedAmount: 0,
      targetAmount: 0,
      isComplete: false,
      coverImage: AppImages.imageMilestoneTrees,
      createdAt: DateTime.now(),
    ),
    Milestone(
      id: "4",
      title: "Tree Growth Monitoring",
      description: "Ensure survival of newly planted trees.",
      order: 4,
      contributors: 0,
      raisedAmount: 0,
      targetAmount: 0,
      isComplete: false,
      coverImage: AppImages.imageMilestoneTrees,
      createdAt: DateTime.now(),
    ),
  ];

  static List<Milestone> milestonesOrphans = [
    // Education for Orphans
    Milestone(
      id: "7_0",
      title: "Fundraising for School Supplies",
      description: "Raise funds to purchase books, stationery, and uniforms.",
      order: 1,
      contributors: 300,
      targetAmount: 15000,
      raisedAmount: 7500,
      isComplete: true,
      coverImage: "assets/images/impact_reports/education.png",
      image: [],
      document: [],
      createdAt: DateTime(2025, 2, 15),
    ),
    Milestone(
      id: "7_1",
      title: "Distribute Supplies",
      description: "Provide school materials to 200 orphans.",
      order: 2,
      contributors: 300,
      targetAmount: 15000,
      raisedAmount: 7500,
      isComplete: false,
      coverImage: "assets/images/impact_reports/education.png",
      image: [],
      document: [],
      createdAt: DateTime(2025, 2, 15),
    ),
    Milestone(
      id: "7_2",
      title: "Tutoring & Mentorship",
      description: "Offer free tutoring and mentorship sessions.",
      order: 3,
      contributors: 300,
      targetAmount: 15000,
      raisedAmount: 7500,
      isComplete: false,
      coverImage: "assets/images/impact_reports/education.png",
      image: [],
      document: [],
      createdAt: DateTime(2025, 2, 15),
    ),
  ];

  static List<Milestone> milestonesMedical = [
    // Medical Aid for Remote Areas
    Milestone(
      id: "9_0",
      title: "Fundraising & Medical Supply Collection",
      description: "Raise funds and collect essential medicines.",
      order: 1,
      contributors: 275,
      targetAmount: 18000,
      raisedAmount: 9000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneMedical,
      image: [],
      document: [],
      createdAt: DateTime(2025, 2, 5),
    ),
    Milestone(
      id: "9_1",
      title: "Mobile Medical Camps",
      description: "Deploy medical teams to provide free healthcare.",
      order: 2,
      contributors: 275,
      targetAmount: 18000,
      raisedAmount: 9000,
      isComplete: false,
      coverImage: AppImages.imageMilestoneMedical,
      image: [],
      document: [],
      createdAt: DateTime(2025, 2, 5),
    ),
    Milestone(
      id: "9_2",
      title: "Health Awareness Workshops",
      description: "Educate communities on hygiene and disease prevention.",
      order: 3,
      contributors: 275,
      targetAmount: 18000,
      raisedAmount: 9000,
      isComplete: false,
      coverImage: AppImages.imageMilestoneMedical,
      image: [],
      document: [],
      createdAt: DateTime(2025, 2, 5),
    ),
  ];

  static List<Milestone> milestonesCleanWater = [
    Milestone(
      id: "10_0",
      title: "Identify Contaminated Areas",
      description: "Survey and analyze water sources in need of purification.",
      order: 1,
      contributors: 320,
      targetAmount: 20000,
      raisedAmount: 10000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneWater,
      image: [],
      document: [],
      createdAt: DateTime(2025, 3, 1),
    ),
    Milestone(
      id: "10_1",
      title: "Install Water Filtration Systems",
      description: "Deploy purification units in affected communities.",
      order: 2,
      contributors: 320,
      targetAmount: 20000,
      raisedAmount: 10000,
      isComplete: false,
      coverImage: AppImages.imageMilestoneWater,
      image: [],
      document: [],
      createdAt: DateTime(2025, 3, 1),
    ),
    Milestone(
      id: "10_2",
      title: "Community Training & Maintenance",
      description: "Educate locals on water safety and system upkeep.",
      order: 3,
      contributors: 320,
      targetAmount: 20000,
      raisedAmount: 10000,
      isComplete: false,
      coverImage: AppImages.imageMilestoneWater,
      image: [],
      document: [],
      createdAt: DateTime(2025, 3, 1),
    ),
  ];

  static List<Milestone> milestonesHomeless = [
    Milestone(
      id: "1",
      title: "Set Up Food Stations",
      description: "Establish community food distribution points.",
      order: 1,
      contributors: 0,
      raisedAmount: 0,
      targetAmount: 0,
      isComplete: true,
      coverImage: "", // Add relevant image if needed
      createdAt: DateTime.now(),
    ),
    Milestone(
      id: "2",
      title: "Provide Temporary Shelter",
      description: "Offer short-term housing for the homeless.",
      order: 2,
      contributors: 0,
      raisedAmount: 0,
      targetAmount: 0,
      isComplete: false,
      coverImage: "",
      createdAt: DateTime.now(),
    ),
    Milestone(
      id: "3",
      title: "Job Placement Assistance",
      description: "Help individuals find employment.",
      order: 3,
      contributors: 0,
      raisedAmount: 0,
      targetAmount: 0,
      isComplete: false,
      coverImage: "",
      createdAt: DateTime.now(),
    ),
  ];

  static List<Milestone> milestonesScholarship = [
    Milestone(
      id: "1",
      title: "Fundraising Campaign",
      description: "Secure funding for scholarship program.",
      order: 1,
      contributors: 0,
      raisedAmount: 0,
      targetAmount: 0,
      isComplete: true,
      coverImage: "", // Add relevant image if needed
      createdAt: DateTime.now(),
    ),
    Milestone(
      id: "2",
      title: "Application & Selection",
      description: "Identify eligible students.",
      order: 2,
      contributors: 0,
      raisedAmount: 0,
      targetAmount: 0,
      isComplete: false,
      coverImage: "",
      createdAt: DateTime.now(),
    ),
    Milestone(
      id: "3",
      title: "Award Scholarships",
      description: "Provide financial aid to selected students.",
      order: 3,
      contributors: 0,
      raisedAmount: 0,
      targetAmount: 0,
      isComplete: false,
      coverImage: "",
      createdAt: DateTime.now(),
    ),
  ];

  static List<Milestone> milestonesRebuild = [
    Milestone(
      id: "1",
      title: "Emergency Aid Distribution",
      description: "Provide immediate shelter and food.",
      order: 1,
      contributors: 0,
      raisedAmount: 0,
      targetAmount: 0,
      isComplete: true,
      coverImage: "", // Add relevant image if needed
      createdAt: DateTime.now(),
    ),
    Milestone(
      id: "2",
      title: "Rebuild Damaged Homes",
      description: "Assist in home reconstruction.",
      order: 2,
      contributors: 0,
      raisedAmount: 0,
      targetAmount: 0,
      isComplete: false,
      coverImage: "",
      createdAt: DateTime.now(),
    ),
    Milestone(
      id: "3",
      title: "Long-Term Housing Support",
      description: "Ensure sustainable housing solutions.",
      order: 3,
      contributors: 0,
      raisedAmount: 0,
      targetAmount: 0,
      isComplete: false,
      coverImage: "",
      createdAt: DateTime.now(),
    ),
  ];
}
