import 'package:fidefund/models/milestone_model.dart';
import 'package:fidefund/utils/app_images.dart';

class MilestoneController {

   static List<Milestone> mockMilestone = [
    Milestone(
      id: "1",
      name: "Saving Stray Dogs in Melaka",
      description: "A campaign to save stray dogs...",
      campaignId: "campaign_1",
      order: 1,
      // category: "Animal Welfare",
      contributors: 120,
      raisedAmount: 5000,
      targetAmount: 10000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneStraydogs,
      createdAt: DateTime(2025, 3, 14),
    ),
    Milestone(
      id: "2",
      name: "E-Gadgets for B40 Students",
      description: "Providing gadgets for underprivileged students...",
      campaignId: "campaign_2",
      order: 2,
      // category: "Education",
      contributors: 200,
      raisedAmount: 8000,
      targetAmount: 15000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneGadgets,
      createdAt: DateTime(2025, 3, 10),
    ),
    Milestone(
      id: "3",
      name: "Flood in East Coast Malaysia",
      description: "Flood relief for affected families...",
      campaignId: "campaign_3",
      order: 1,
      // category: "Disaster Relief",
      contributors: 300,
      raisedAmount: 12000,
      targetAmount: 20000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneFlood,
      createdAt: DateTime(2025, 2, 7),
    ),
    Milestone(
      id: "4",
      name: "Tree Planting Initiative",
      description: "Planting trees to combat deforestation...",
      campaignId: "campaign_1",
      order: 1,
      // category: "Environment",
      contributors: 150,
      raisedAmount: 6000,
      targetAmount: 12000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneTrees,
      createdAt: DateTime(2025, 1, 25),
    ),
    Milestone(
      id: "5",
      name: "Orphanage Education Support",
      description: "Providing learning materials for orphanages...",
      campaignId: "campaign_2",
      order: 1,
      // category: "Children",
      contributors: 180,
      raisedAmount: 7000,
      targetAmount: 13000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneOrphanage,
      createdAt: DateTime(2025, 3, 5),
    ),
    Milestone(
      id: "6",
      name: "Medical Aid for Rural Areas",
      description: "Supplying essential medicine to remote villages...",
      campaignId: "campaign_3",
      order: 1,
      // category: "Health",
      contributors: 220,
      raisedAmount: 9500,
      targetAmount: 15000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneMedical,
      createdAt: DateTime(2025, 2, 28),
    ),
    Milestone(
      id: "7",
      name: "Clean Water for Villages",
      description: "Building wells to provide clean drinking water...",
      campaignId: "campaign_1",
      order: 1,
      // category: "Water & Sanitation",
      contributors: 250,
      raisedAmount: 11000,
      targetAmount: 18000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneWater,
      createdAt: DateTime(2025, 2, 15),
    ),
    Milestone(
      id: "8",
      name: "Feeding the Homeless",
      description: "Providing meals and shelter for the homeless...",
      campaignId: "campaign_2",
      order: 1,
      // category: "Social Welfare",
      contributors: 280,
      raisedAmount: 13000,
      targetAmount: 20000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneHomeless,
      createdAt: DateTime(2025, 1, 30),
    ),
    Milestone(
      id: "9",
      name: "Scholarships for Underprivileged Students",
      description: "Offering scholarships to talented students in need...",
      campaignId: "campaign_3",
      order: 1,
      // targetAmount: "Education",
      contributors: 320,
      raisedAmount: 15000,
      targetAmount: 25000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneScholarship,
      createdAt: DateTime(2025, 1, 20),
    ),
    Milestone(
      id: "10",
      name: "Rebuilding Homes After Fire",
      description: "Helping families rebuild after a devastating fire...",
      campaignId: "campaign_1",
      order: 1,
      // category: "Disaster Relief",
      contributors: 350,
      raisedAmount: 16000,
      targetAmount: 30000,
      isComplete: true,
      coverImage: AppImages.imageMilestoneRebuild,
      createdAt: DateTime(2025, 3, 2),
    ),
  ];


}