import 'package:fidefund/models/transaction_model.dart';

class TransactionController {
  final List<Transaction> mockTransaction = [
    Transaction(
      hash: "0x1234abcd",
      campaignTitle: "Education Fund",
      senderAddress: "0xABC123",
      receiverAddress: "0xDEF456",
      amount: 10.5,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 3, 11),
    ),
    Transaction(
      hash: "0x5678efgh",
      campaignTitle: "Community Support",
      senderAddress: "0xABC123",
      receiverAddress: "0xXYZ789",
      amount: 5.2,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 3, 10),
    ),
    Transaction(
      hash: "0x9abcijkl",
      campaignTitle: "Healthcare Relief",
      senderAddress: "0xLMN345",
      receiverAddress: "0xPQR678",
      amount: 7.8,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 3, 9),
    ),
    // Additional 20 mock transactions
    Transaction(
      hash: "0xa1b2c3d4",
      campaignTitle: "Food Aid Program",
      senderAddress: "0xF12G34",
      receiverAddress: "0xH56J78",
      amount: 15.0,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 3, 8),
    ),
    Transaction(
      hash: "0xe5f6g7h8",
      campaignTitle: "Disaster Relief",
      senderAddress: "0xK98L76",
      receiverAddress: "0xM54N32",
      amount: 22.5,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 3, 7),
    ),
    Transaction(
      hash: "0xijklmnop",
      campaignTitle: "Children's Welfare",
      senderAddress: "0xP21Q43",
      receiverAddress: "0xR65S87",
      amount: 30.0,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 3, 6),
    ),
    Transaction(
      hash: "0xzyxwvuts",
      campaignTitle: "Water Sanitation",
      senderAddress: "0xT43U65",
      receiverAddress: "0xV87W98",
      amount: 12.8,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 3, 5),
    ),
    Transaction(
      hash: "0xabcdef12",
      campaignTitle: "Animal Rescue",
      senderAddress: "0xX32Y54",
      receiverAddress: "0xZ76A98",
      amount: 18.0,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 3, 4),
    ),
    Transaction(
      hash: "0x3456ghij",
      campaignTitle: "Medical Assistance",
      senderAddress: "0xB21C43",
      receiverAddress: "0xD65E87",
      amount: 25.5,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 3, 3),
    ),
    Transaction(
      hash: "0xklmnopqr",
      campaignTitle: "Scholarship Program",
      senderAddress: "0xF12G56",
      receiverAddress: "0xH34J78",
      amount: 50.0,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 3, 2),
    ),
    Transaction(
      hash: "0xstuvwx12",
      campaignTitle: "Renewable Energy Project",
      senderAddress: "0xK45L67",
      receiverAddress: "0xM89N01",
      amount: 60.3,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 3, 1),
    ),
    Transaction(
      hash: "0x9876abcd",
      campaignTitle: "Refugee Assistance",
      senderAddress: "0xP34Q56",
      receiverAddress: "0xR78S90",
      amount: 35.4,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 2, 28),
    ),
    Transaction(
      hash: "0x1234wxyz",
      campaignTitle: "Senior Citizen Support",
      senderAddress: "0xT65U87",
      receiverAddress: "0xV98W10",
      amount: 40.6,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 2, 27),
    ),
    Transaction(
      hash: "0x2468mnop",
      campaignTitle: "Mental Health Awareness",
      senderAddress: "0xX23Y45",
      receiverAddress: "0xZ67A89",
      amount: 28.9,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 2, 26),
    ),
    Transaction(
      hash: "0xabcdef99",
      campaignTitle: "Art & Culture Fund",
      senderAddress: "0xB32C54",
      receiverAddress: "0xD76E98",
      amount: 33.2,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 2, 25),
    ),
    Transaction(
      hash: "0x1234uvwx",
      campaignTitle: "Homeless Shelter Project",
      senderAddress: "0xF65G87",
      receiverAddress: "0xH98J10",
      amount: 44.8,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 2, 24),
    ),
    Transaction(
      hash: "0x3456qrst",
      campaignTitle: "Women Empowerment",
      senderAddress: "0xK32L54",
      receiverAddress: "0xM76N98",
      amount: 20.7,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 2, 23),
    ),
    Transaction(
      hash: "0x7890abcd",
      campaignTitle: "Youth Skill Training",
      senderAddress: "0xP12Q34",
      receiverAddress: "0xR56S78",
      amount: 26.9,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 2, 22),
    ),
    Transaction(
      hash: "0x5678efgh",
      campaignTitle: "Community Garden Project",
      senderAddress: "0xT43U65",
      receiverAddress: "0xV87W98",
      amount: 19.5,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 2, 21),
    ),
    Transaction(
      hash: "0x9012ijkl",
      campaignTitle: "Clean Water Initiative",
      senderAddress: "0xX12Y34",
      receiverAddress: "0xZ56A78",
      amount: 42.1,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 2, 20),
    ),
    Transaction(
      hash: "0x3456mnop",
      campaignTitle: "Green Earth Movement",
      senderAddress: "0xB21C43",
      receiverAddress: "0xD65E87",
      amount: 29.3,
      currency: "MYR",
      status: 1.0,
      createdAt: DateTime(2025, 2, 19),
    ),
  ];
}
