import 'package:fidefund/models/transaction_model.dart';

class TransactionController {
  final List<Transaction> mockTransaction = [
    Transaction(
      hash: "0x1234abcd",
      campaignTitle: "Education Fund",
      senderAddress: "0xABC123",
      receiverAddress: "0xDEF456",
      amountMYR: 10.5,
      amountCrypto: 0.0025,
      Cryptocurrency: "ETH",
      status: 1.0,
      createdAt: DateTime(2025, 3, 11),
    ),
    Transaction(
      hash: "0x5678efgh",
      campaignTitle: "Community Support",
      senderAddress: "0xABC123",
      receiverAddress: "0xXYZ789",
      amountMYR: 5.2,
      amountCrypto: 0.00098,
      Cryptocurrency: "BTC",
      status: 1.0,
      createdAt: DateTime(2025, 3, 10),
    ),
    Transaction(
      hash: "0x9abcijkl",
      campaignTitle: "Healthcare Relief",
      senderAddress: "0xLMN345",
      receiverAddress: "0xPQR678",
      amountMYR: 7.8,
      amountCrypto: 0.003,
      Cryptocurrency: "BNB",
      status: 1.0,
      createdAt: DateTime(2025, 3, 9),
    ),
    Transaction(
      hash: "0xa1b2c3d4",
      campaignTitle: "Food Aid Program",
      senderAddress: "0xF12G34",
      receiverAddress: "0xH56J78",
      amountMYR: 15.0,
      amountCrypto: 0.005,
      Cryptocurrency: "SOL",
      status: 1.0,
      createdAt: DateTime(2025, 3, 8),
    ),
    Transaction(
      hash: "0xe5f6g7h8",
      campaignTitle: "Disaster Relief",
      senderAddress: "0xK98L76",
      receiverAddress: "0xM54N32",
      amountMYR: 22.5,
      amountCrypto: 0.0012,
      Cryptocurrency: "BTC",
      status: 1.0,
      createdAt: DateTime(2025, 3, 7),
    ),
    Transaction(
      hash: "0xijklmnop",
      campaignTitle: "Children's Welfare",
      senderAddress: "0xP21Q43",
      receiverAddress: "0xR65S87",
      amountMYR: 30.0,
      amountCrypto: 0.0078,
      Cryptocurrency: "ETH",
      status: 1.0,
      createdAt: DateTime(2025, 3, 6),
    ),
    Transaction(
      hash: "0xzyxwvuts",
      campaignTitle: "Water Sanitation",
      senderAddress: "0xT43U65",
      receiverAddress: "0xV87W98",
      amountMYR: 12.8,
      amountCrypto: 0.004,
      Cryptocurrency: "BNB",
      status: 1.0,
      createdAt: DateTime(2025, 3, 5),
    ),
    Transaction(
      hash: "0xabcdef12",
      campaignTitle: "Animal Rescue",
      senderAddress: "0xX32Y54",
      receiverAddress: "0xZ76A98",
      amountMYR: 18.0,
      amountCrypto: 0.0021,
      Cryptocurrency: "SOL",
      status: 1.0,
      createdAt: DateTime(2025, 3, 4),
    ),
    Transaction(
      hash: "0x3456ghij",
      campaignTitle: "Medical Assistance",
      senderAddress: "0xB21C43",
      receiverAddress: "0xD65E87",
      amountMYR: 25.5,
      amountCrypto: 0.0015,
      Cryptocurrency: "BTC",
      status: 1.0,
      createdAt: DateTime(2025, 3, 3),
    ),
    Transaction(
      hash: "0xklmnopqr",
      campaignTitle: "Scholarship Program",
      senderAddress: "0xF12G56",
      receiverAddress: "0xH34J78",
      amountMYR: 50.0,
      amountCrypto: 0.01,
      Cryptocurrency: "ETH",
      status: 1.0,
      createdAt: DateTime(2025, 3, 2),
    ),
    Transaction(
      hash: "0xstuvwx12",
      campaignTitle: "Renewable Energy Project",
      senderAddress: "0xK45L67",
      receiverAddress: "0xM89N01",
      amountMYR: 60.3,
      amountCrypto: 0.009,
      Cryptocurrency: "BNB",
      status: 1.0,
      createdAt: DateTime(2025, 3, 1),
    ),
    Transaction(
      hash: "0x9876abcd",
      campaignTitle: "Refugee Assistance",
      senderAddress: "0xP34Q56",
      receiverAddress: "0xR78S90",
      amountMYR: 35.4,
      amountCrypto: 0.0028,
      Cryptocurrency: "SOL",
      status: 1.0,
      createdAt: DateTime(2025, 2, 28),
    ),
    Transaction(
      hash: "0x1234wxyz",
      campaignTitle: "Senior Citizen Support",
      senderAddress: "0xT65U87",
      receiverAddress: "0xV98W10",
      amountMYR: 40.6,
      amountCrypto: 0.0036,
      Cryptocurrency: "ETH",
      status: 1.0,
      createdAt: DateTime(2025, 2, 27),
    ),
    Transaction(
      hash: "0x2468mnop",
      campaignTitle: "Mental Health Awareness",
      senderAddress: "0xX23Y45",
      receiverAddress: "0xZ67A89",
      amountMYR: 28.9,
      amountCrypto: 0.0023,
      Cryptocurrency: "BTC",
      status: 1.0,
      createdAt: DateTime(2025, 2, 26),
    ),
    Transaction(
      hash: "0xabcdef99",
      campaignTitle: "Art & Culture Fund",
      senderAddress: "0xB32C54",
      receiverAddress: "0xD76E98",
      amountMYR: 33.2,
      amountCrypto: 0.0041,
      Cryptocurrency: "BNB",
      status: 1.0,
      createdAt: DateTime(2025, 2, 25),
    ),
    Transaction(
      hash: "0x1234uvwx",
      campaignTitle: "Homeless Shelter Project",
      senderAddress: "0xF65G87",
      receiverAddress: "0xH98J10",
      amountMYR: 44.8,
      amountCrypto: 0.0062,
      Cryptocurrency: "SOL",
      status: 1.0,
      createdAt: DateTime(2025, 2, 24),
    ),
  ];
}
